# Generated by Django 3.0 on 2020-08-02 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sts', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subjectclass',
            unique_together={('teacher', 'student')},
        ),
    ]
