# Generated by Django 3.0 on 2020-08-09 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sts', '0003_auto_20200802_2010'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subjectclass',
            unique_together=set(),
        ),
    ]
