# Generated by Django 3.0 on 2020-08-09 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sts', '0004_auto_20200809_1537'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subjectclass',
            unique_together={('teacher', 'student')},
        ),
    ]
